version: "3.7"

services:

    service_1:
        image: tdcole/service_1:latest
        environment: 
            - MYSQL_HOST=${MYSQL_HOST}
            - MYSQL_USER=${MYSQL_USER}
            - MYSQL_PASSWORD=${MYSQL_PASSWORD}
            - MYSQL_DB=${MYSQL_DB}
        networks:
            - ingress
        deploy:
            replicas: 3

    service_2:
        image: tdcole/service_2:latest
        networks:
            - ingress
        deploy:
            replicas: 3

    service_3:
        image: tdcole/service_3:latest
        networks:
            - ingress
        deploy:
            replicas: 3

    service_4:
        image: tdcole/service_4:latest
        networks:
            - ingress
        deploy:
            replicas: 3

    service_nginx:
        image: tdcole/nginx:latest
        ports:
            - "80:80"
        networks:
            - ingress
        depends_on:
            - service_1
            - service_2
            - service_3
            - service_4
        deploy:
            replicas: 3

networks:
    ingress:
        driver: overlay